### ISSUE TITLE
no linux support

### ISSUE THREAD

**Issue by Errorcrafter** [Bakdooro/Bakdooro-Installer#3]
## Describe your idea
we need linux support and i dont have linux to test it. Unknown-User2 or AcaiBerii pls add linux support kthx

## Expected behaviour
Instead of this, Bakdooro should work on Linux.

## Alternatives
n/a

## Before you submit
- [x] I have made sure that this feature request is not a duplicate.
- [x] This feature request is applicable on the latest versions of Bakdooro.
- [x] This is a FEATURE REQUEST and not some retarded cope about how someone used Bakdooro to grief my shitty P2W server.

**Comment by prokube** [comment]
> * [x]  This is a FEATURE REQUEST and not some retarded cope about how someone used Bakdooro to grief my shitty P2W server.

cool

**Comment by prokube** [comment]
> EDIT: nvm, its not and im stoopid https://github.com/3V1/linux-token-logger/blob/main/main.py i fear what we will have to do should someone require mac support lmaooooo

Hewwo thewe ;w;
